name: Build Windows Binary

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet packages (if needed)
        run: nuget restore HackMe.sln

      - name: Build with MSBuild
        run: msbuild HackMe.sln /p:Configuration=Release /p:Platform=x64

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: windows-binary
          path: "**/Release/*.exe"
